devtools::install_version("e1071", "1.6-8")
devtools::install_version("gbm", "2.1.3")
devtools::install_version("randomForest", "4.6-12")
devtools::install_version("xgboost", "0.6.4.1")
devtools::install_version("caret", "6.0-78")
devtools::install_version("yardstick", "0.0.1")
devtools::install_version("tidyverse", "1.2.1")
